# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Amount to Pay')),
                ('payment_tye', models.CharField(default=b'Cash', max_length=255, verbose_name='Payment type')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('description', models.TextField(default=b'Description', verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Amount to Pay')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('description', models.TextField(default=b'Description', verbose_name='Description')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('date_time_end', models.DateTimeField(blank=True, verbose_name='Date and Time of Delivery')),
                ('folio_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Folio Number')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total Cost')),
                ('time_to_complete', models.PositiveIntegerField(default=5, verbose_name='Time to Complete')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_set', to='branches.Branch')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location_set', to='branches.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_set', to='branches.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='workshopstatus',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.WorkshopTicket'),
        ),
        migrations.AddField(
            model_name='workshopstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshopservices',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.WorkshopTicket'),
        ),
        migrations.AddField(
            model_name='workshopservices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshopproduct',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.WorkshopTicket'),
        ),
        migrations.AddField(
            model_name='workshopproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshoppayment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.WorkshopTicket'),
        ),
        migrations.AddField(
            model_name='workshoppayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
