# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Date and Time')),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Amount to Pay')),
                ('folio_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Folio Number')),
                ('type', models.IntegerField(choices=[(30, b'one_month'), (60, b'two_month'), (90, b'three_month')], default=30, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayawayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('folio_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Folio Number')),
                ('payment_type', models.CharField(default=b'Cash', max_length=255, verbose_name='Payment Type')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
                ('layaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layaway.Layaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayawayProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Price')),
                ('layaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layaway.Layaway')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
