# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('slug', models.CharField(default=b'branch', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default=b'branch name', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_pre', models.TextField(blank=True, max_length=255, null=True)),
                ('ticket_post', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BranchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'branch type', max_length=255, unique=True)),
                ('description', models.CharField(default=b'type description', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='details',
            field=models.ManyToManyField(blank=True, to='branches.BranchDetail'),
        ),
        migrations.AddField(
            model_name='branch',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.BranchType'),
        ),
    ]
