# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ticket_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ticket_pre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
