# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Precio')),
                ('equivalency', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Equivalencia')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(verbose_name='Codigo')),
                ('type', models.SlugField(choices=[(b'bodega', b'Bodega'), (b'area', b'Area'), (b'linea', b'Linea'), (b'marca', b'Marca'), (b'toons', b'Toons')], verbose_name='Tipo')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'detail name', max_length=255, verbose_name='Name')),
                ('description', models.CharField(default=b'detail description', max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('type', models.CharField(choices=[(b'10k', b'10K'), (b'14k', b'14K'), (b'plata', b'Plata')], max_length=5, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=3, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(default=b'nombre', max_length=255, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('telephone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono 1')),
                ('telephone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono 2')),
                ('type', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'detail name', max_length=255, verbose_name='Name')),
                ('description', models.CharField(default=b'detail description', max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='details',
            field=models.ManyToManyField(to='products.ProviderDetail'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(blank=True, to='products.ProductDetail'),
        ),
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductLine'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Provider'),
        ),
    ]
